source "https://api.berkshelf.com"

cookbook "git"
cookbook "zsh"
cookbook "vim"
cookbook "tmux"
cookbook "nodejs"
cookbook "rake"
cookbook "root_ssh_agent", git: "git@github.com:dergachev/chef_root_ssh_agent.git"
cookbook "parshap", git: "git@github.com:parshap/parshap-cookbook.git"
