#!/bin/bash

set -e

# Originally from https://gist.github.com/ruliana/5079371
# This script will bootstrap a machine with Ruby and Chef

apt_install() {
	sudo apt-get install --yes --no-install-recommends $@
}

apt_update() {
	sudo apt-get -y update
	touch /tmp/apt_update_last
}

# apt-get update once per day
apt_update_if_stale() {
	touch -d "-1 day" /tmp/apt_update_limit
	if [ /tmp/apt_update_limit -nt /tmp/apt_update_last ]
	then
		apt_update
	fi
}

apt_update_if_stale

# Install add-apt-repository
apt_install software-properties-common

# Add Ruby PPA
ubuntu_codename=$(lsb_release --codename | cut -f2)
if [ ! -f /etc/apt/sources.list.d/brightbox-ruby-ng-${ubuntu_codename}.list ]
then
	sudo apt-add-repository ppa:brightbox/ruby-ng
	# Always apt-get update after adding a ppa
	apt_update
fi

# Install Ruby
apt_install ruby2.4 ruby2.4-dev

# Install build tools
apt_install build-essential

# Install Chef
chef_version=13.3.42
chef_version_current=$(sudo chef-solo --version 2>/dev/null | awk ' { sub(/Chef: /, ""); print }')
if [ "$chef_version_current" != "$chef_version" ]
then
	sudo gem install --no-ri --no-rdoc chef -v $chef_version
fi
